local MouseIcons = {
	Arrow = {
		Plugin = "rbxasset://SystemCursors/Arrow",
		Client = ""
	},
	PointingHand = {
		Plugin = "rbxasset://SystemCursors/PointingHand",
		Client = ""
	},
	OpenHand = {
		Plugin = "rbxasset://SystemCursors/OpenHand",
		Client = ""
	},
	ClosedHand = {
		Plugin = "rbxasset://SystemCursors/ClosedHand",
		Client = ""
	},
	IBeam = {
		Plugin = "rbxasset://SystemCursors/IBeam",
		Client = ""
	},
	SizeNS = {
		Plugin = "rbxasset://SystemCursors/SizeNS",
		Client = ""
	},
	SizeEW = {
		Plugin = "rbxasset://SystemCursors/SizeEW",
		Client = ""
	},
	SizeNESW = {
		Plugin = "rbxasset://SystemCursors/SizeNESW",
		Client = "rbxassetid://18861122283"
	},
	SizeNWSE = {
		Plugin = "rbxasset://SystemCursors/SizeNWSE",
		Client = "rbxassetid://18861122023"
	},
	SizeAll = {
		Plugin = "rbxasset://SystemCursors/SizeAll",
		Client = ""
	},
	SplitNS = {
		Plugin = "rbxasset://SystemCursors/SplitNS",
		Client = "rbxassetid://18861162030"
	},
	SplitEW = {
		Plugin = "rbxasset://SystemCursors/SplitEW",
		Client = "rbxassetid://18861162494"
	},
	Forbidden = {
		Plugin = "rbxasset://SystemCursors/Forbidden",
		Client = ""
	},
	Wait = {
		Plugin = "rbxasset://SystemCursors/Wait",
		Client = ""
	},
	Busy = {
		Plugin = "rbxasset://SystemCursors/Busy",
		Client = ""
	},
	Cross = {
		Plugin = "rbxasset://SystemCursors/Cross",
		Client = "rbxasset://15556263648"
	},
}

return MouseIcons